### ISSUE TITLE
Roadmap to Deployment

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/domus-tdd-api#8]
- [ ] We choose Apache Jena for Triple Storage
- [ ] Configure the Docker setup to use [docker swarm](https://docs.docker.com/reference/cli/docker/stack/) where we expose all the ports and the services can choose to be proxied. Only the HTTP Endpoint for the API will be exposed.
- [ ] Configure a cronjob to delete the database entries every week so that we avoid people using it permanently as a "free service"
- [ ] Reset the Eclipse Server. We stick to Ubuntu and same ports. Other services we run (test things) should be ready as well.
- [ ] Start advertisement!

@relu91 let us know if something is not fine here

**Comment by relu91** [comment]
Seems a good plan!
